# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: julian
  admin_email: juliansugiarto12@gmail.com
  admin_password: xaveriusnatson
  domain_name: www.juliansugiarto.com
  secret_key_base: 719dd6d76102a463a44c22c81ae6b41106de6b93730029db43703a71c632d91937265ebc00bc781358c26ba5ffa1ef4d5c2c03e45bf94cc43a709e9bd07e3994

test:
  domain_name: example.com 
  secret_key_base: f7113b4af23d69646d554787cb2dc4de4d5c815ad0ff13ac9b4ac6a41e54cfdf13c0cb828269ed1ef2d0cc5a6f5358f8ba45eede46426c90b0307c75abdc8272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
